debug: true

http_server:
  port: 2967

k8s:
  host: "https://172.17.4.99:443"
  ssl:
    ca: "/etc/deployit/ssl/ca.pem"
    key: "/etc/deployit/ssl/admin-key.pem"
    cert: "/etc/deployit/ssl/admin.pem"